# Generated by Django 5.0.4 on 2024-04-19 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0003_appointments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Agendada"),
                            ("F", "Finalizada"),
                            ("C", "Cancelada"),
                            ("I", "Iniciada"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="doctors.appointments",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente - Consulta",
                "verbose_name_plural": "Paciente - Consultas",
            },
        ),
    ]
