# Generated by Django 5.0.4 on 2024-04-16 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialty", models.CharField(max_length=100)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="icons")),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crm", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=15)),
                ("street", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                ("street_number", models.IntegerField()),
                ("rg", models.ImageField(upload_to="rgs")),
                ("medical_identity", models.ImageField(upload_to="cim")),
                ("photo", models.ImageField(upload_to="fotos_perfil")),
                ("description", models.TextField(blank=True, null=True)),
                ("appointment_price", models.FloatField(default=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="doctors.specialties",
                    ),
                ),
            ],
        ),
    ]
